import {
  Booking,
  BookingsStats,
  DashboardStats,
  Gig,
  ModelProfile,
  ModelsStats,
  PartnerActivityItem,
  PartnerActivityStats,
  RecentScanActivity,
  UserActivityItem,
  UserActivityStats,
} from '../types';

export const INITIAL_DASHBOARD_STATS: DashboardStats = {
  conversionRate: {
    points: 1,
    lkr: 200,
  },
  pointsIssued: 12450,
  pointsIssuedChange: '+8% vs yesterday',
  activeScansToday: 142,
  newRegistrationsToday: 24,
};

export const INITIAL_BOOKINGS_STATS: BookingsStats = {
  newBookings: 16,
  pendingBookings: 16,
  todaysLiveBookings: 4,
};

export const INITIAL_MODELS_STATS: ModelsStats = {
  activeModels: 24,
  totalModels: 96,
  pendingGigs: 8,
  pendingPayments: 2,
};

export const INITIAL_USER_ACTIVITY_STATS: UserActivityStats = {
  totalUsers: 96,
  todaysDeductions: 24000,
  todaysDeposits: 14000,
};

export const INITIAL_PARTNER_ACTIVITY_STATS: PartnerActivityStats = {
  totalPartners: 136,
  todaysDeductions: 24000,
  totalDeductions: 126000,
};

export const INITIAL_RECENT_ACTIVITIES: RecentScanActivity[] = [
  {
    id: 'act-1',
    member: 'Sarah Jenkins',
    memberId: 'NX-682-A',
    pointsAwarded: 99,
    time: 'Just now',
    memberAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'act-2',
    member: 'Michael Chen',
    memberId: 'NX-104-B',
    pointsAwarded: 99,
    time: '10 mins ago',
    memberAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'act-3',
    member: 'Elena Rodriguez',
    memberId: 'NX-990-X',
    pointsAwarded: 0,
    time: '45 mins ago',
    memberAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'act-4',
    member: 'David Kim',
    memberId: 'NX-412-K',
    pointsAwarded: 50,
    time: '1 hour ago',
    memberAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-1',
    bookingCode: 'BK-682-A',
    customer: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    studioRoom: 'ST-A',
    dateTime: '12:20 PM Oct 29, 2025',
    duration: '4 hours',
    status: 'Pending',
    amount: 'LKR 18,000',
  },
  {
    id: 'bk-2',
    bookingCode: 'BK-682-A',
    customer: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    studioRoom: 'ST-A',
    dateTime: '12:20 PM Oct 29, 2025',
    duration: '4 hours',
    status: 'Approved',
    amount: 'LKR 28,000',
  },
  {
    id: 'bk-3',
    bookingCode: 'BK-682-A',
    customer: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    studioRoom: 'ST-A',
    dateTime: '12:20 PM Oct 29, 2025',
    duration: '4 hours',
    status: 'Completed',
    amount: 'LKR 40,000',
  },
  {
    id: 'bk-4',
    bookingCode: 'BK-682-A',
    customer: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    studioRoom: 'ST-A',
    dateTime: '12:20 PM Oct 29, 2025',
    duration: '4 hours',
    status: 'Approved',
    amount: 'LKR 18,000',
  },
  {
    id: 'bk-5',
    bookingCode: 'BK-682-A',
    customer: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    studioRoom: 'ST-A',
    dateTime: '12:20 PM Oct 29, 2025',
    duration: '4 hours',
    status: 'Pending',
    amount: 'LKR 22,500',
  },
  {
    id: 'bk-6',
    bookingCode: 'BK-682-A',
    customer: 'Sarah Jenkins',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    studioRoom: 'ST-A',
    dateTime: '12:20 PM Oct 29, 2025',
    duration: '4 hours',
    status: 'Pending',
    amount: 'LKR 18,000',
  },
];

export const INITIAL_GIGS  = [
  {
    id: 'gig-1',
    modelId: 'sarah-jenkins',
    title: 'Basic Fashion Shoot',
    tag: 'Fashion & Portfolio',
    rate: 'LKR 4500/hr',
    description: 'Perfect for personal branding, social media, and portfolio updates with professional studio lighting.',
    bookingId: 'BK-682-A',
    dateTime: '12:20 PM Oct 29, 2025',
    duration: '4 hours',
    amount: 'LKR 18,000',
    status: 'pending',
    coverImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400&auto=format&fit=crop',
    ],
  },
  {
    id: 'gig-2',
    modelId: 'sarah-jenkins',
    title: 'Premium Fashion Shoot',
    tag: 'Commercial & Lookbook',
    rate: 'LKR 7000/hr',
    description: 'Ideal for models, influencers, and fashion campaigns with multiple outfit changes and creative direction.',
    bookingId: 'BK-683-B',
    dateTime: '02:00 PM Nov 02, 2025',
    duration: '4 hours',
    amount: 'LKR 28,000',
    status: 'active',
    coverImage: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=800&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=400&auto=format&fit=crop',
    ],
  },
  {
    id: 'gig-3',
    modelId: 'sarah-jenkins',
    title: 'Editorial Fashion Shoot',
    tag: 'Editorial & Magazine',
    rate: 'LKR 10000/hr',
    description: 'High-end fashion photography for magazines, lookbooks, and commercial promotions with advanced styling setups.',
    bookingId: 'BK-684-C',
    dateTime: '10:00 AM Nov 10, 2025',
    duration: '6 hours',
    amount: 'LKR 60,000',
    status: 'active',
    coverImage: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?q=80&w=800&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=400&auto=format&fit=crop',
    ],
  },
];

export const INITIAL_MODELS  = [
  {
    id: 'sarah-jenkins',
    name: 'Sarah Jenkins',
    handle: '@sarahjenkins',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    email: 'sarahjenkins@gmail.com',
    phone: '+94 77 123 4567',
    bio: 'Professional model specializing in fashion campaigns, editorials, and brand promotions.',
    specialty: 'sports-wear model',
    availability: 'Available',
    uploadedTime: 'Just now',
    approvedGigsCount: 2,
    pendingGigsCount: 1,
    pendingGigs: [INITIAL_GIGS[0]],
    activeGigs: [INITIAL_GIGS[1], INITIAL_GIGS[2]],
  },
  {
    id: 'michael-chen',
    name: 'Michael Chen',
    handle: '@michaelchen',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    email: 'mchen@gmail.com',
    phone: '+94 77 234 5678',
    bio: 'Fitness and casual fashion model with over 4 years of studio and outdoor shoot experience.',
    specialty: 'fitness & lifestyle',
    availability: 'Available',
    uploadedTime: 'Just now',
    approvedGigsCount: 1,
    pendingGigsCount: 1,
    pendingGigs: [],
    activeGigs: [],
  },
  {
    id: 'elena-rodriguez',
    name: 'Elena Rodriguez',
    handle: '@elena_r',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
    email: 'elena.rodriguez@gmail.com',
    phone: '+94 77 345 6789',
    bio: 'Runway and high-fashion model working with top apparel brands and magazine editorials.',
    specialty: 'high-fashion runway',
    availability: 'Unavailable',
    uploadedTime: 'Just now',
    approvedGigsCount: 4,
    pendingGigsCount: 0,
    pendingGigs: [],
    activeGigs: [],
  },
  {
    id: 'david-kim',
    name: 'David Kim',
    handle: '@davidkim',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
    email: 'davidkim@gmail.com',
    phone: '+94 77 456 7890',
    bio: 'Commercial brand ambassador and video talent for lifestyle and tech commercials.',
    specialty: 'commercial & talent',
    availability: 'Available',
    uploadedTime: 'Just now',
    approvedGigsCount: 3,
    pendingGigsCount: 2,
    pendingGigs: [],
    activeGigs: [],
  },
];

export const INITIAL_USER_ACTIVITIES: UserActivityItem[] = [
  {
    id: 'ua-1',
    member: 'Sarah Jenkins',
    memberId: 'NX-682-A',
    amount: -1400,
    partner: 'Island Monkey',
    time: 'Just now',
  },
  {
    id: 'ua-2',
    member: 'Sarah Jenkins',
    memberId: 'NX-682-A',
    amount: 2400,
    partner: 'Carriage',
    time: '45 mins ago',
  },
  {
    id: 'ua-3',
    member: 'Sarah Jenkins',
    memberId: 'NX-682-A',
    amount: 2400,
    partner: 'Island Monkey',
    time: '45 mins ago',
  },
  {
    id: 'ua-4',
    member: 'Sarah Jenkins',
    memberId: 'NX-682-A',
    amount: 2400,
    partner: 'Island Monkey',
    time: '45 mins ago',
  },
  {
    id: 'ua-5',
    member: 'Sarah Jenkins',
    memberId: 'NX-682-A',
    amount: -1400,
    partner: 'Carriage',
    time: 'Just now',
  },
  {
    id: 'ua-6',
    member: 'Sarah Jenkins',
    memberId: 'NX-682-A',
    amount: 2400,
    partner: 'Island Monkey',
    time: '45 mins ago',
  },
];

export const INITIAL_PARTNER_ACTIVITIES: PartnerActivityItem[] = [
  {
    id: 'pa-1',
    partnerName: 'Carriage',
    customerName: 'Sarah Jenkins',
    customerId: 'NX-682-A',
    amount: -1400,
    time: 'Just now',
  },
  {
    id: 'pa-2',
    partnerName: 'Pepper st',
    customerName: 'Sarah Jenkins',
    customerId: 'NX-682-A',
    amount: -1400,
    time: 'Just now',
  },
  {
    id: 'pa-3',
    partnerName: 'Pepper st',
    customerName: 'Sarah Jenkins',
    customerId: 'NX-682-A',
    amount: -1400,
    time: '45 mins ago',
  },
  {
    id: 'pa-4',
    partnerName: 'FOA',
    customerName: 'Sarah Jenkins',
    customerId: 'NX-682-A',
    amount: -1400,
    time: '45 mins ago',
  },
  {
    id: 'pa-5',
    partnerName: 'Pepper st',
    customerName: 'Sarah Jenkins',
    customerId: 'NX-682-A',
    amount: -1400,
    time: '45 mins ago',
  },
];
